FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["Recommerce.csproj", "./"]
RUN dotnet restore "Recommerce.csproj"
COPY . .
WORKDIR "/src/"
RUN dotnet build "Recommerce.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Recommerce.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Recommerce.dll"]
